import os

START_LEVEL = 1
MAX_LEVEL = 10

TRAIN_NAME = f"SUDOKU"

OUTPUT_DIR = os.path.join("output", TRAIN_NAME)
TENSORBOARD_TRAIN_LOG = os.path.join(OUTPUT_DIR, "logs", "train")

MODEL_NAME = "sudoku.zip"
CHECKPOINT_NAME = "checkpoint"

MODEL_PATH = os.path.join(OUTPUT_DIR, MODEL_NAME)

MAX_TIMESTEPS = 50
TOTAL_TIMESTEPS = 300000000
NUM_AGENTS = 10
CHECK_FREQ = 500
REWARD_THRESHOLD = 0.95
RENDER_GUI = False
